services:
  portfolio-frontend:
    container_name: portfolio
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    restart: always
    networks:
      - homelab_default



networks:
  homelab_default:
    external: true
