services:
  portfolio-frontend:
    container_name: portfolio
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
       - ./.env.production
    ports:
      - "5173:80"
    stdin_open: true
    tty: true
    restart: always
